# Generated by Django 4.2.4 on 2023-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100)),
                ('email', models.CharField(max_length=2000)),
                ('phone', models.CharField(max_length=2000)),
            ],
        ),
    ]
