# Generated by Django 4.2.4 on 2023-08-09 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_about_description_alter_about_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='point_one',
            field=models.TextField(default='point_1'),
        ),
        migrations.AddField(
            model_name='about',
            name='point_three',
            field=models.TextField(default='point_3'),
        ),
        migrations.AddField(
            model_name='about',
            name='point_two',
            field=models.TextField(default='point_2'),
        ),
    ]
